### ISSUE TITLE
InvalidParameters: invalid parameter(s) 

### ISSUE THREAD

**Issue by mkaliyannan** [vatesfr/xo-server-backup-reports#9]
I tried this module and I am getting following errors:

register plugin backup-reports: InvalidParameters: invalid parameter(s)
    at _default._callee5$ (/source/xo-mixins/plugins.js:147:12)
    at tryCatch (/apps/xo-server/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/apps/xo-server/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/apps/xo-server/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/apps/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /apps/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/apps/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at _default.<anonymous> (/apps/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at _default._configurePlugin (/apps/xo-server/dist/xo-mixins/plugins.js:348:22)
    at /source/xo-mixins/plugins.js:91:22
    at run (/apps/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /apps/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/apps/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by julien-f** [comment]
I don't think it's a fatal error, once you have configured the plugin through the interface, the error should disappear :)
